ku-ring/ku-ring-backend-web

src/test/java/com/kustacks/kuring/acceptance/AcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/CategoryAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/CategoryStep.java, src/test/java/com/kustacks/kuring/acceptance/CommonStep.java, src/test/java/com/kustacks/kuring/acceptance/FeedbackAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/NoticeAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/NoticeStep.java
실패 케이스도 작성해보았습니다! 이전과 거의 동일합니다.
다만, 원래 인수테스트로 세부적인 예외, 실패하는 경우 까지 검증하는것은 좋은 방향이 아니라 생각됩니다.
(사실 사용자가 offset값에 -1을 전달하면서 앱을 사용하는 story는 말이 안되거든요)
예외 테스트는 사실 단위테스트에서 들어가야하지만, 지금은 단위테스트 작성이 어렵다 생각되어 일단 API 수준 테스트로 처리하였습니다!
=> [Test] Fail acceptance test 추가

src/main/java/com/kustacks/kuring/notice/domain/DepartmentNoticeQueryRepository.java, src/main/java/com/kustacks/kuring/notice/domain/DepartmentNoticeQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/RealEstateNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/liberal_art/GeologyDept.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java, src/main/resources/application.yml
최근 공지를 업데이트 해주는 updater가 정상적으로 id검증을 하지 못하고 있었다.
위 메서드의 원래 내가 의도했던 목적은 : 
limit의 수만큼 최신 공지의 id를 가져오는 메서드였다.
하지만 order by에서 오름차순으로 정렬해둔것이 문제가 되었다.
즉, 숫자가 높을 수록 최신의 공지 id인데, 오름 차순으로 조회하고 있었으니... => 가장 오래된 공지 id를 limit의 수만큼 조회하고 있었던것
오름차순으로 정렬한 후 limit의 수만큼이 아닌, 모든 공지의 id를 가지고 오도록 메서드를 변경하였다.
=> [Fix-#33] LatestNoticeUpdater cant valid duplicate

src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
(관련 이슈 : #64 )
해당 이슈는 Client측에서 파라미터 명이 잘못 전달되고 있었다고 한다.
서버 측에서는 테스트 케이스만 추가하고 끝
=> [Fix-#64] Cant store user department 

src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LatestPageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/DeptInfo.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java
부동산 학과의 경우 한번에 모든 공지를 로딩해올수가 없었다.
전체 공지페이지가 68페이지 인데, 68번의 요청을 보내고 있었다.
따라서 부동산 학과의 경우 단일페이지 스크랩만 제공하도록 변경하였다.
=> [Fix-#68] Post not supported 수정하기

src/main/resources/db/migration/V230823__Delete_notice_foreign_key.sql
=> [fix-#77] Notice의 CategoryName에 대한 외래키 제약조건 제거

README.md, src/main/java/com/kustacks/kuring/admin/common/dto/FeedbackDto.java, src/main/java/com/kustacks/kuring/notice/domain/DepartmentNotice.java, src/main/java/com/kustacks/kuring/notice/domain/Notice.java, src/main/java/com/kustacks/kuring/notice/domain/Url.java, src/main/java/com/kustacks/kuring/user/business/FeedbackService.java, src/main/java/com/kustacks/kuring/user/domain/FeedbackRepository.java, src/main/java/com/kustacks/kuring/user/domain/User.java, src/main/java/com/kustacks/kuring/user/domain/UserQueryRepository.java, src/main/java/com/kustacks/kuring/user/domain/UserQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/user/domain/UserRepository.java
close #110 
1. URL 부분 검증 pattern 변경, pattern 정적으로 미리 컴파일 해두기
2. User ID의 Getter 제거
3. User에 Repository + 조회 전용 QueryDsl 로 변경
4. readme 정렬
=> [Refactor] user refactor

src/main/java/com/kustacks/kuring/message/application/service/FirebaseSubscribeService.java
verifyIdToken의 경우 클라이언트 측에서 별도의 ID 토큰을 생성하여 전달해주어야 하기 때문에 일단 기존의 방식으로 변경한다
=> [Fix] FirebaseSubscribeService의 토큰 검증 로직 변경

scripts/start.sh, src/main/java/com/kustacks/kuring/common/exception/handler/CommonExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/exception/FirebaseExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/firebase/FirebaseAdapter.java, src/main/java/com/kustacks/kuring/message/application/service/FirebaseNotificationService.java, src/main/java/com/kustacks/kuring/worker/scrap/DepartmentNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisHomepageNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/client/ProxyJsoupClient.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LatestPageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/NoticeUpdateSupport.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/logback-spring.xml, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/message/adapter/in/event/MessageAdminEventListenerTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdaterTest.java
기존의 2.6.9가 prod환경에서 정상적으로 배포되지 않는 문제가 있다.
이를 수정한 스크립트를 사용한다.
refactor: Log level 변경
refactor: 환경 별 Log Setting 변경 완료
refactor: 로그파일 저장 기간을 10일로 단축
refactor(FirebaseNotificationService): message 변환 로직을 메서드로 추출
test(AdminAcceptanceTest): 관리자의 공지 전송 인수테스트 작성
=> version 2.6.10

build.gradle, src/main/java/com/kustacks/kuring/ai/adapter/out/model/InMemoryQueryAiModelAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/InMemoryVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/application/service/RAGQueryService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/test/java/com/kustacks/kuring/acceptance/AiAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AiStep.java
=> [Feat] Change response type #200

build.gradle, src/main/java/com/kustacks/kuring/ai/adapter/out/model/InMemoryQueryAiModelAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/InMemoryVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/application/service/RAGQueryService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/test/java/com/kustacks/kuring/acceptance/AiAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AiStep.java
* setting: reactor-test 의존성 추가
* test(AiAcceptanceTest): 질문하는 인수테스트 StepVerifier를 사용하도록 변경
* feat(RAGQueryService): RAGQueryService 내부에서 직접 예외처리 구현
기존에는 ExceptionHandler 로 처리하였지만, 이는 JSON 응답에 적합하지 Flux<String>을 반환하기에 적합하지 않는것 같다. 따라서 직접적으로 Service 에서 예외를 처리하여 반환한다.
* setting: ai model 과 embedding model 을 외부 환경변수로 분리
=> version 2.7.2

src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserQueryApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/dto/UserAIAskCountResponse.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserAIAskCountResult.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java, src/main/java/com/kustacks/kuring/user/domain/User.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
=> [Feat] Ai count api #215

src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserQueryApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/dto/UserAIAskCountResponse.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserAIAskCountResult.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java, src/main/java/com/kustacks/kuring/user/domain/User.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
사용자의 질문 횟수를 조회하는 API 기능 추가
* test(UserAcceptanceTest): 사용자의 질문 가능 횟수를 조회하는 인수테스트 작성
* feat(UserQueryApiV2): 사용자 질문 횟수 조회 API 구현 완료
=> version 2.9.0

src/main/java/com/kustacks/kuring/admin/adapter/in/web/AdminCommandApiV2.java, src/main/java/com/kustacks/kuring/admin/adapter/out/event/AdminAiEventAdapter.java, src/main/java/com/kustacks/kuring/admin/application/port/in/AdminCommandUseCase.java, src/main/java/com/kustacks/kuring/admin/application/port/out/AiEventPort.java, src/main/java/com/kustacks/kuring/admin/application/service/AdminCommandService.java, src/main/java/com/kustacks/kuring/ai/adapter/in/event/DataEmbeddingEventListener.java, src/main/java/com/kustacks/kuring/ai/adapter/in/event/dto/DataEmbeddingEvent.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/InMemoryVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/application/port/in/RAGCommandUseCase.java, src/main/java/com/kustacks/kuring/ai/application/port/out/CommandVectorStorePort.java, src/main/java/com/kustacks/kuring/ai/application/service/RAGCommandService.java, src/main/java/com/kustacks/kuring/alert/application/port/in/dto/DataEmbeddingCommand.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java
Admin이 직접 txt파일로 embedding 작업을 수행하는 API 구현
=> version 2.10.0

src/main/resources/ai/prompts/rag-prompt-template.st
=> version 2.10.1

.gitignore, build.gradle, src/main/java/com/kustacks/kuring/staff/adapter/out/persistence/StaffRepository.java, src/main/java/com/kustacks/kuring/worker/update/staff/StaffDataSynchronizer.java, src/main/java/com/kustacks/kuring/worker/update/staff/StaffUpdater.java, src/main/java/com/kustacks/kuring/worker/update/staff/dto/StaffScrapResults.java, src/main/resources/db/migration/V241130__Add_position_to_staff.sql, src/test/java/com/kustacks/kuring/worker/update/staff/StaffUpdaterTest.java
#149 
이전 PR에서 default 값이 잘못 들어가서 "0"으로 들어가는 현상을 수정하기 위해 ddl수정했습니닷.
PR머지 전 dev 서버DB에서 flyway 기록 삭제, 만들어져있는 position column 삭제하려고 합니당
이를 위해 DB에 있는 전체학과를 조회하여 비교하도록 구현했습니다. 로컬에서 정상적으로 비교, 삭제되는것 확인했습니다!
=> Feat : 직위 추가 ddl 수정, 교직원 스크랩 로직 및 주기 변경

src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserCommandApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/dto/UserPasswordModifyRequest.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/dto/UserPasswordResetRequest.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserCommandUseCase.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserPasswordModifyCommand.java, src/main/java/com/kustacks/kuring/user/application/service/UserCommandService.java, src/main/java/com/kustacks/kuring/user/domain/RootUser.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
- 비밀번호 변경 로직 추가했습니다.
- Access-Token 유무에 따라 변경이나 초기화가 가능합니다.
1. 초기화 시
`Request Body`
```json
{
"email" : "client@konkuk.ac.kr",
"password" : "newPassword"
}
````
3. 변경 시
`Request Header`
Authorization : Bearer {access-token}
`Request Body`
```json
{
"password" : "newPassword"
}
=> Feat : 비밀번호 변경(초기화) API 추가

src/main/java/com/kustacks/kuring/auth/authentication/AuthorizationExtractor.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/common/exception/code/ErrorCode.java, src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeCommandApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserCommandApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserQueryApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/dto/UserInfoResponse.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserInfoResult.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java, src/main/java/com/kustacks/kuring/user/domain/RootUser.java, src/test/java/com/kustacks/kuring/acceptance/NoticeAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
- Jwt Access-Token 기반으로 유저 기본 정보 조회 API 추가했습니다.
- 토큰이 유효하지 않을 시 응답코드를 400 -> 401로 변경했습니다.
클라이언트 측에서 400이면 오류 이유를 알기 어렵다고 생각해서 수정했습니다.
=> Feat : 유저 정보 조회 API 추가

src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/user/adapter/in/web/UserCommandApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/RootUserRepository.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/UserPersistenceAdapter.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/UserRepository.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserCommandUseCase.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserWithdrawCommand.java, src/main/java/com/kustacks/kuring/user/application/port/out/RootUserCommandPort.java, src/main/java/com/kustacks/kuring/user/application/port/out/RootUserQueryPort.java, src/main/java/com/kustacks/kuring/user/application/port/out/UserQueryPort.java, src/main/java/com/kustacks/kuring/user/application/service/UserCommandService.java, src/main/java/com/kustacks/kuring/user/domain/RootUser.java, src/main/resources/db/migration/V250318__Add_deleted_to_root_user.sql, src/main/resources/db/migration/V250319__Drop_unique_key_from_email.sql, src/test/java/com/kustacks/kuring/acceptance/EmailAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/NoticeAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
- RootUser 회원 탈퇴 기능이 추가되었습니다.
- 회원 탈퇴 시 RootUser로 로그인 되어있는 User를 로그아웃합니다.
- SoftDelete 방식으로 구현됐습니다.
-  root_user에 deleted 컬럼이 추가됐습니다.
- root_user 테이블의 email의 unique 속성을 삭제했습니다.(재가입 가능)
> 여러개 작업하다가 PR 쪼개려다보니 커밋이 살짝 요상합니다 😢
=> Feat : 회원탈퇴 기능 추가

src/main/java/com/kustacks/kuring/common/utils/generator/NicknameGenerator.java, src/main/java/com/kustacks/kuring/common/utils/generator/RandomGenerator.java, src/main/java/com/kustacks/kuring/common/utils/generator/VerificationCodeGenerator.java, src/main/java/com/kustacks/kuring/email/adapter/in/web/EmailCommandApiV2.java, src/main/java/com/kustacks/kuring/email/application/port/in/EmailCommandUseCase.java, src/main/java/com/kustacks/kuring/email/application/service/EmailCommandService.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/RootUserQueryRepository.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/RootUserQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/RootUserRepository.java, src/main/java/com/kustacks/kuring/user/adapter/out/persistence/UserPersistenceAdapter.java, src/main/java/com/kustacks/kuring/user/application/port/out/RootUserQueryPort.java, src/main/java/com/kustacks/kuring/user/application/service/UserCommandService.java, src/test/java/com/kustacks/kuring/acceptance/EmailAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/EmailStep.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/common/utils/generator/NicknameGeneratorTest.java, src/test/java/com/kustacks/kuring/common/utils/generator/RandomGeneratorTest.java, src/test/java/com/kustacks/kuring/common/utils/generator/VerificationCodeGeneratorTest.java, src/test/java/com/kustacks/kuring/email/application/service/EmailCommandUseCaseTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java
- 인증 이메일 전송 시 `password-reset`과 `signup`으로 구분하여 회원가입 시와 비밀번호 초기화 시 사용하는 API를 분리했습니다.
- RandomGenerator를 수정하여 VerificationCodeGenerator와 NicknameGenerator를 구분하여 용도에 맞는 생성 클래스를 추가하였습니다.
- Generator클래스의 테스트 코드를 추가했습니다.
=> Feat: 비밀번호 초기화 시 인증코드 전송 로직 분리#247

src/main/java/com/kustacks/kuring/email/adapter/in/web/EmailCommandApiV2.java, src/main/java/com/kustacks/kuring/email/application/service/EmailCommandService.java, src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java, src/test/java/com/kustacks/kuring/acceptance/EmailAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/EmailStep.java
- 비밀번호 초기화 인증코드 이메일 전송 시 헤더 or body값으로 이메일 받도록 수정
- 만약, 둘다 값이 없는경우 400에러 발생
- 비밀번호 초기화 인증코드 이메일 전송 시 이메일 검증 로직 추가(회원가입 된 사용자, 학교 이메일 도메인)
- 헤더 or body값만 있는 경우, 둘다 없는 경우에 대한 인수 테스트 추가
- 자율전공 -> 자유전공 오타 수정
> 관련 이슈 : #253
=> Fix : 비밀번호 초기화 인증코드 이메일 전송 방식 수정 및 검증 추가 #253

src/main/java/com/kustacks/kuring/admin/adapter/in/web/AdminCommandApiV2.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/notice/application/port/in/BadWordInitProcessor.java, src/main/java/com/kustacks/kuring/notice/application/port/in/BadWordLoadUseCase.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeCommandService.java, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AdminStep.java
- 금칙어 로드 로직을 BadWordLoadUseCase로 분리했습니다.
- NoticeCommandServie에서 PostConstruct간 `BadWordLoadUseCase.loadBadWords()`를 통해 자동으로 로드합니다.
- 필요 시 Admin Api를 통해 리로드합니다.
#264
=> Feat: Admin 금칙어 로드 API 추가

src/main/java/com/kustacks/kuring/admin/adapter/in/web/AdminCommandApiV2.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/notice/application/port/in/BadWordInitProcessor.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeCommandService.java, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AdminStep.java
* refactor: 금칙어 로드 UseCase 추가
* refactor: PostConstruct 시 금칙어 로드 로직 변경
* feat: Admin을 통해 금칙어 로드 하는 API 추가
* test: Admin 금칙어 로드 API 인수 테스트 추가
* test: Admin 금칙어 로드 API 인수 테스트 경로 변경
* refactor: BadWordLoadUseCase 인터페이스명 변경(BadWordInitProcessor)
* refactor: BadWordInitProcessor 인터페이스명 변경에 따른 메서드명 변경
=> version 2.13.1

build.gradle, src/main/java/com/kustacks/kuring/calendar/domain/AcademicEvent.java, src/main/java/com/kustacks/kuring/calendar/domain/Transparent.java, src/main/resources/db/migration/V250824__Create_academic_event_table.sql
#281 
- ICS 포맷 파싱을 위한 iCal4j 의존성 추가했습니다.
- 학사일정 저장 위한 academic_event 테이블 추가했습니다.
- iCal4j로 파싱해온 데이터 목록 중 일부 필요한 내용이라 판단되는 내용만 테이블에 추가했습니다.
- 알람보내지 않더라도 모든 내용을 저장하는 것이 나을거 같아 우선 다 저장하고, notifyEnabled로 구분하려합니다.
- Transparent의 경우 OPAQUE(중요일정)  TRANSPARENT(사소한 일정)으로 기본적으로 구분되어있어 저장했습니다.
관련해서 테스트 코드와 출력 예시 첨부합니다
```java
package com.kustacks.kuring;
import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import net.fortuna.ical4j.model.Calendar;
import net.fortuna.ical4j.model.component.VEvent;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
public class IcsParsingTest {
final static String calendarUrl = …
```
=> Feat: 학사일정 엔티티, 테이블 DDL 추가 및 iCal4j 의존성 추가

src/main/java/com/kustacks/kuring/worker/notification/AcademicEventNotificationScheduler.java, src/main/java/com/kustacks/kuring/worker/update/calendar/AcademicEventUpdater.java
- 학사일정 알림과 업데이트 두가지 스케쥴링의 업데이트 시간이 서로 바뀌어 있는 문제를 수정했습니다.
=> Fix: 학사일정 알림 및 업데이트 시간 수정
