src/main/java/com/kustacks/kuring/kuapi/notice/NoticeUpdater.java, src/main/java/com/kustacks/kuring/kuapi/notice/RenewSessionKuisAuthManager.java, src/test/java/com/kustacks/kuring/kuapi/notice/RenewSessionKuisAuthManagerTest.java
=> fix: 세션 획득 방식 변경으로 인한 로그인 실패 시 공지 알림 일시 중단

build.gradle, src/main/java/com/kustacks/kuring/controller/AdminController.java, src/main/java/com/kustacks/kuring/controller/dto/AdminMessageDTO.java, src/main/java/com/kustacks/kuring/controller/dto/FCMMessageDTO.java, src/main/java/com/kustacks/kuring/controller/dto/NoticeMessageDTO.java, src/main/java/com/kustacks/kuring/error/ErrorCode.java, src/main/java/com/kustacks/kuring/kuapi/notice/NoticeUpdater.java, src/main/java/com/kustacks/kuring/service/AdminService.java, src/main/java/com/kustacks/kuring/service/AdminServiceImpl.java, src/main/java/com/kustacks/kuring/service/FirebaseService.java, src/main/java/com/kustacks/kuring/util/converter/NoticeEntityToNoticeMessageDTOConverter.java
푸시알림 포맷에 type 속성 추가. 이에 따른 FirebaseService, AdminService 등 변경
=> version 1.1.2

README.md
**중요**
API 가이드가 제공되고 있으므로 api key 업데이트 asap
=> `README.md` 에 스크린샷 이미지 추가

src/main/java/com/kustacks/kuring/category/domain/Category.java, src/main/java/com/kustacks/kuring/config/MappedBeanConfig.java, src/main/java/com/kustacks/kuring/config/RestTemplateConfig.java, src/main/java/com/kustacks/kuring/kuapi/api/ApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/notice/KuisNoticeApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/notice/LibraryNoticeApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/notice/NoticeApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/staff/EachDeptStaffApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/staff/KuStaffApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/staff/RealEstateStaffApiClient.java, src/main/java/com/kustacks/kuring/kuapi/api/staff/StaffApiClient.java, src/main/java/com/kustacks/kuring/kuapi/notice/NoticeUpdater.java, src/main/java/com/kustacks/kuring/kuapi/notice/dto/response/LibraryNoticeDTO.java, src/main/java/com/kustacks/kuring/kuapi/notice/dto/response/LibraryNoticeResponseDTO.java, src/main/java/com/kustacks/kuring/kuapi/scrap/StaffScraper.java, src/main/java/com/kustacks/kuring/notice/domain/Notice.java, src/main/java/com/kustacks/kuring/notice/domain/NoticeRepository.java, src/main/resources/constants.properties, src/test/java/com/kustacks/kuring/kuapi/api/notice/KuisNoticeApiClientRetryTest.java, src/test/java/com/kustacks/kuring/kuapi/api/notice/KuisNoticeApiClientTest.java, src/test/java/com/kustacks/kuring/kuapi/api/staff/StaffScraperTest.java, src/test/java/com/kustacks/kuring/kuapi/notice/ParsingKuisAuthManagerTest.java
(관련 이슈 : #29 )
도서관 홈페이지 개편 이후, 변경된 URL을 적용하고
일부 로직을 리팩토링 한다.
=> [Fix-#29] 도서관 URL 수정

.github/workflows/build.yml, build.gradle
=> [Feat-#38] SonarCloud 도입

src/main/java/com/kustacks/kuring/category/domain/CategoryName.java, src/main/java/com/kustacks/kuring/notice/business/NoticeService.java, src/main/java/com/kustacks/kuring/notice/presentation/NoticeControllerV2.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/KuisNoticeApiClient.java, src/test/java/com/kustacks/kuring/acceptance/NoticeStep.java
=> [Refactor-#43] change page name

src/main/java/com/kustacks/kuring/common/firebase/FirebaseService.java, src/main/java/com/kustacks/kuring/worker/update/notice/CategoryNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java
=> [Refactor-#61] NoticeUpdate 에서 공통되는 로직을 FirebaseService로 추출

build.gradle, src/main/java/com/kustacks/kuring/admin/presentation/AdminControllerV1.java, src/main/java/com/kustacks/kuring/common/exception/handler/CommonExceptionHandler.java, src/main/java/com/kustacks/kuring/common/interceptor/AuthInterceptor.java, src/main/java/com/kustacks/kuring/message/firebase/FirebaseService.java, src/main/java/com/kustacks/kuring/message/firebase/exception/handler/FirebaseExceptionHandler.java, src/main/java/com/kustacks/kuring/worker/scrap/DepartmentNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/StaffScraper.java, src/main/java/com/kustacks/kuring/worker/scrap/client/ProxyJsoupClient.java, src/main/java/com/kustacks/kuring/worker/scrap/client/auth/ParsingKuisAuthManager.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LatestPageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LibraryNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/scrap/parser/staff/StaffEachDeptHtmlParser.java, src/main/java/com/kustacks/kuring/worker/update/notice/CategoryNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/staff/StaffUpdater.java, src/main/java/com/kustacks/kuring/worker/update/user/UserUpdater.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/java/com/kustacks/kuring/notice/domain/NoticeTest.java, src/test/resources/application.yml
관련 정리글 : https://blogshine.tistory.com/677
=> [Refactor-#80] log level change

src/main/java/com/kustacks/kuring/notice/domain/NoticeQueryRepositoryImpl.java
QueryDsl method들에 Transactional 에너테이션을 추가해주었다!
=> [Fix-#83] 메서드에 Transactional 처리 추가

src/main/java/com/kustacks/kuring/config/HttpSessionConfig.java
QueryDsl 메서드에 Transactional 처리가 안되고 있던 문제 해결
=> version 2.2.2

src/main/java/com/kustacks/kuring/admin/presentation/AdminQueryApiV2.java, src/main/java/com/kustacks/kuring/auth/AuthConfig.java, src/main/java/com/kustacks/kuring/auth/authorization/AuthenticationPrincipal.java, src/main/java/com/kustacks/kuring/auth/authorization/AuthenticationPrincipalArgumentResolver.java, src/main/java/com/kustacks/kuring/auth/exception/AuthExceptionHandler.java, src/main/java/com/kustacks/kuring/auth/exception/RoleAuthenticationException.java, src/main/java/com/kustacks/kuring/auth/secured/Secured.java, src/main/java/com/kustacks/kuring/auth/secured/SecuredAnnotationChecker.java, src/test/java/com/kustacks/kuring/acceptance/AcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/tool/DatabaseConfigurator.java
=> [Feat-#89] Admin role base

src/main/java/com/kustacks/kuring/admin/common/AdminProperties.java, src/main/java/com/kustacks/kuring/admin/common/InitAdmin.java, src/main/java/com/kustacks/kuring/admin/facade/AdminCommandFacade.java, src/main/java/com/kustacks/kuring/feedback/business/FeedbackService.java, src/main/java/com/kustacks/kuring/message/firebase/FirebaseService.java, src/main/java/com/kustacks/kuring/user/business/UserService.java, src/main/resources/constants.properties
=> [Feat-#93] Dev server add suffix

src/main/java/com/kustacks/kuring/admin/facade/AdminCommandFacade.java, src/main/java/com/kustacks/kuring/auth/AuthConfig.java, src/main/java/com/kustacks/kuring/auth/dto/UserRegisterRequest.java, src/main/java/com/kustacks/kuring/auth/exception/RegisterException.java, src/main/java/com/kustacks/kuring/auth/handler/UserRegisterFailureHandler.java, src/main/java/com/kustacks/kuring/auth/handler/UserRegisterSuccessHandler.java, src/main/java/com/kustacks/kuring/auth/interceptor/AdminTokenAuthenticationFilter.java, src/main/java/com/kustacks/kuring/auth/interceptor/AuthenticationNonChainingFilter.java, src/main/java/com/kustacks/kuring/auth/interceptor/UserRegisterNonChainingFilter.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/feedback/business/FeedbackService.java, src/main/java/com/kustacks/kuring/message/firebase/FirebaseService.java, src/main/java/com/kustacks/kuring/message/firebase/ServerProperties.java, src/main/java/com/kustacks/kuring/user/business/UserService.java, src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/UserStep.java
=> [Feat-#95] User signup filter

src/main/java/com/kustacks/kuring/admin/common/dto/AdminNotificationDto.java, src/main/java/com/kustacks/kuring/admin/common/dto/RealNotificationRequest.java, src/main/java/com/kustacks/kuring/admin/facade/AdminCommandFacade.java, src/main/java/com/kustacks/kuring/worker/update/staff/StaffUpdater.java, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java
close #97 
Admin의 커스텀공지에 url필드 추가
=> [Feat-#97] Admin noti add url

src/main/java/com/kustacks/kuring/worker/scrap/client/auth/KuisAuthManager.java, src/main/java/com/kustacks/kuring/worker/scrap/client/auth/ParsingKuisAuthManager.java, src/main/java/com/kustacks/kuring/worker/update/notice/CategoryNoticeUpdater.java, src/test/java/com/kustacks/kuring/worker/notice/ParsingKuisAuthManagerTest.java
=> [Fix-#99] Multi thread session renew fix

README.md
=> [Docs] Readme 파일을 최신화 한다

README.md
=> [Docs-#102] 리팩토링과 성능 개선 내용을 리드미 메인에 추가한다 (#104)

README.md
기존의 readme 파일을 리팩토링한 점과 개선사항 위주로 업데이트 한다
=> docs(README): 리드미 CD flow 사진 변경

README.md
=> docs(README): 리드미 CD flow 사진 변경 (#107)

README.md, build.gradle, src/main/java/com/kustacks/kuring/worker/update/staff/StaffUpdater.java, src/main/resources/application.yml, src/test/resources/application-test.yml
close #116 
더이상 사용하지 않는 Sentry에 대한 의존성을 제거한다.
이후 별도의 로그관리 시스템을 추가할 예정
=> [Refactor] delete sentry

.github/workflows/dev.yml, .github/workflows/prod.yml
=> [Setting] Github Action 스크립트에 환경 추가

src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeQueryApiV2.java
=> fix(NoticeQueryApiV2#getNotices): 학과공지 조회에서 important필드 결여로 인한 문제

src/main/java/com/kustacks/kuring/worker/scrap/client/notice/KuisHomepageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/scrap/noticeinfo/KuisHomepageNoticeInfo.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdater.java, src/test/java/com/kustacks/kuring/worker/scrap/KuisHomepageNoticeScraperTemplateTest.java, src/test/java/com/kustacks/kuring/worker/scrap/client/notice/KuisHomepageNoticeApiClientTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdaterTest.java, src/test/resources/notice/student-notice-no-total-count-2024.html
=> [Fix] notice parse error #154

src/main/java/com/kustacks/kuring/worker/parser/notice/KuisHomepageNoticeHtmlParser.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/dto/response/CommonNoticeFormatDto.java, src/test/java/com/kustacks/kuring/worker/parser/NoticeHtmlParserTemplateTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java, src/test/resources/notice/job-notice-2024.html
=> [Fix] notice id parse error #157

src/main/java/com/kustacks/kuring/worker/dto/ComplexNoticeFormatDto.java, src/main/java/com/kustacks/kuring/worker/parser/notice/RowsDto.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/test/java/com/kustacks/kuring/worker/scrap/KuisHomepageNoticeScraperTemplateTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdaterTest.java
=> version 2.6.4

README.md, src/main/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticePersistenceAdapter.java, src/main/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticeQueryRepository.java, src/main/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticeQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/notice/application/port/out/NoticeCommandPort.java, src/main/java/com/kustacks/kuring/notice/application/port/out/dto/NoticeDto.java, src/main/java/com/kustacks/kuring/notice/domain/NoticeDateTime.java, src/main/java/com/kustacks/kuring/user/application/port/out/dto/BookmarkDto.java, src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/business/BusinessAdministrationDept.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/test/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticeRepositoryTest.java, src/test/java/com/kustacks/kuring/notice/domain/NoticeDateTimeTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdaterTest.java
=> [Refactor] notice date #169

src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java
=> [Feat]: NoticeQueryService의 findAllNoticeByContent 에서 시간은 제거하고 날짜만 반환

src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java
=> version 2.6.8

scripts/start.sh, src/main/java/com/kustacks/kuring/common/exception/handler/CommonExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/exception/FirebaseExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/firebase/FirebaseAdapter.java, src/main/java/com/kustacks/kuring/message/application/service/FirebaseNotificationService.java, src/main/java/com/kustacks/kuring/worker/scrap/DepartmentNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisHomepageNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/client/ProxyJsoupClient.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LatestPageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/NoticeUpdateSupport.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/logback-spring.xml, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/message/adapter/in/event/MessageAdminEventListenerTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdaterTest.java
- 로그의 level을 변경한다
- 프로덕션에서 SQL 로그를 제거한다
- 프로덕션에서 Log를 날짜별 파일로 분리하여 저장하도록 변경
- 프로덕션에서 10일이 지나는 경우 로그 파일을 삭제하도록 변경
=> [Refactor] log refactor

scripts/start.sh, src/main/java/com/kustacks/kuring/common/exception/handler/CommonExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/exception/FirebaseExceptionHandler.java, src/main/java/com/kustacks/kuring/message/adapter/out/firebase/FirebaseAdapter.java, src/main/java/com/kustacks/kuring/message/application/service/FirebaseNotificationService.java, src/main/java/com/kustacks/kuring/worker/scrap/DepartmentNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisHomepageNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/KuisNoticeScraperTemplate.java, src/main/java/com/kustacks/kuring/worker/scrap/client/ProxyJsoupClient.java, src/main/java/com/kustacks/kuring/worker/scrap/client/notice/LatestPageNoticeApiClient.java, src/main/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdater.java, src/main/java/com/kustacks/kuring/worker/update/notice/NoticeUpdateSupport.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/logback-spring.xml, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/message/adapter/in/event/MessageAdminEventListenerTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisHomepageNoticeUpdaterTest.java, src/test/java/com/kustacks/kuring/worker/update/notice/KuisNoticeUpdaterTest.java
* refactor: Log level 변경
* refactor: 환경 별 Log Setting 변경 완료
* refactor: 로그파일 저장 기간을 10일로 단축
* refactor(FirebaseNotificationService): message 변환 로직을 메서드로 추출
* test(AdminAcceptanceTest): 관리자의 공지 전송 인수테스트 작성
=> version 2.6.9

src/main/java/com/kustacks/kuring/admin/application/service/AdminCommandService.java, src/main/java/com/kustacks/kuring/message/application/service/FirebaseNotificationService.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java, src/main/java/com/kustacks/kuring/staff/application/service/StaffQueryService.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java
=> version 2.6.11

src/main/java/com/kustacks/kuring/ai/adapter/out/model/InMemoryQueryAiModelAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/worker/parser/notice/KuisHomepageNoticeTextParser.java, src/main/java/com/kustacks/kuring/worker/parser/notice/NoticeTextParserTemplate.java, src/main/java/com/kustacks/kuring/worker/parser/notice/PageTextDto.java, src/test/java/com/kustacks/kuring/acceptance/AiAcceptanceTest.java, src/test/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapterTest.java, src/test/java/com/kustacks/kuring/worker/parser/NoticeTextParserTemplateTest.java
=> [Feat] vector add date #197

src/main/java/com/kustacks/kuring/ai/adapter/out/model/InMemoryQueryAiModelAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/worker/parser/notice/KuisHomepageNoticeTextParser.java, src/main/java/com/kustacks/kuring/worker/parser/notice/NoticeTextParserTemplate.java, src/main/java/com/kustacks/kuring/worker/parser/notice/PageTextDto.java, src/test/java/com/kustacks/kuring/acceptance/AiAcceptanceTest.java, src/test/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapterTest.java, src/test/java/com/kustacks/kuring/worker/parser/NoticeTextParserTemplateTest.java
공지를 vector에 저장할때 metadate로 날짜도 추가하도록 변경
향후 필터링 조건 으로 사용 가능
=> version 2.7.1

src/main/java/com/kustacks/kuring/admin/adapter/in/web/AdminCommandApiV2.java, src/main/java/com/kustacks/kuring/admin/adapter/out/event/AdminAiEventAdapter.java, src/main/java/com/kustacks/kuring/admin/application/port/in/AdminCommandUseCase.java, src/main/java/com/kustacks/kuring/admin/application/port/out/AiEventPort.java, src/main/java/com/kustacks/kuring/admin/application/service/AdminCommandService.java, src/main/java/com/kustacks/kuring/ai/adapter/in/event/DataEmbeddingEventListener.java, src/main/java/com/kustacks/kuring/ai/adapter/in/event/dto/DataEmbeddingEvent.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/ChromaVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/adapter/out/persistence/InMemoryVectorStoreAdapter.java, src/main/java/com/kustacks/kuring/ai/application/port/in/RAGCommandUseCase.java, src/main/java/com/kustacks/kuring/ai/application/port/out/CommandVectorStorePort.java, src/main/java/com/kustacks/kuring/ai/application/service/RAGCommandService.java, src/main/java/com/kustacks/kuring/alert/application/port/in/dto/DataEmbeddingCommand.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java
=> feat(RAGCommandService): 어드민이 직접 학습시키는 API 구현 완료

src/main/resources/ai/prompts/rag-prompt-template.st
=> fix: prompt 변경

src/main/java/com/kustacks/kuring/ai/adapter/in/web/RAGQueryApiV2.java, src/main/java/com/kustacks/kuring/ai/adapter/out/event/RAGEventAdapter.java, src/main/java/com/kustacks/kuring/ai/application/port/out/RAGEventPort.java, src/main/java/com/kustacks/kuring/ai/application/service/RAGQueryService.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeCommandApiV2.java, src/main/java/com/kustacks/kuring/user/adapter/in/event/UserCommandEventListener.java, src/main/java/com/kustacks/kuring/user/adapter/in/event/dto/UserAskedQuestionEvent.java, src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java
=> [Refactor] Change status code #245

src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java, src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/sanghuo_elective/KULiberalStudiesDept.java, src/test/java/com/kustacks/kuring/acceptance/CategoryAcceptanceTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java
=> Feat/add ku free #250

src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java, src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/sanghuo_elective/KULiberalStudiesDept.java, src/test/java/com/kustacks/kuring/acceptance/CategoryAcceptanceTest.java, src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java, src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java
* feat: 자율전공 추가
* setting: ChromaDB 도커 이미지 버전 명시
=> [Feat] add ku free #250 (#251)

src/main/java/com/kustacks/kuring/notice/domain/Comment.java
=> Fix(Comment): 생성자 인자 순서 변경

src/main/java/com/kustacks/kuring/notice/domain/Comment.java
=> version 2.11.1

src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeQueryApiV2.java, src/main/java/com/kustacks/kuring/notice/adapter/in/web/dto/CommentDetailResponse.java, src/main/java/com/kustacks/kuring/notice/application/port/in/NoticeCommentReadingUseCase.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserInfoResult.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java, src/test/java/com/kustacks/kuring/acceptance/NoticeAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/NoticeStep.java
=> [Feat] Comment own #259

src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeQueryApiV2.java, src/main/java/com/kustacks/kuring/notice/adapter/in/web/dto/CommentDetailResponse.java, src/main/java/com/kustacks/kuring/notice/application/port/in/NoticeCommentReadingUseCase.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java, src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserInfoResult.java, src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java, src/test/java/com/kustacks/kuring/acceptance/NoticeAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/NoticeStep.java
* test: 로그인한 사용자의 경우 본인의 댓글을 확인할 수 있도록 하는 테스트 작성
* feat(UserInfoResult): 사용자 ID필드 추가
* feat(NoticeQueryService): findComments 호출시 사용자 본인의 댓글은 boolean 필드로 확인할 수 있도록 구현
=> version 2.12.0

src/main/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticeQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/notice/application/port/in/dto/NoticeContentSearchResult.java, src/main/java/com/kustacks/kuring/notice/application/port/out/dto/NoticeSearchDto.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java, src/test/java/com/kustacks/kuring/archunit/DependencyRuleTests.java
=> [Feat] add search comment id #265

src/main/java/com/kustacks/kuring/notice/adapter/out/persistence/NoticeQueryRepositoryImpl.java, src/main/java/com/kustacks/kuring/notice/application/port/in/dto/NoticeContentSearchResult.java, src/main/java/com/kustacks/kuring/notice/application/port/out/dto/NoticeSearchDto.java, src/main/java/com/kustacks/kuring/notice/application/service/NoticeQueryService.java, src/test/java/com/kustacks/kuring/archunit/DependencyRuleTests.java
* feat: 검색시 조회되는 공지 id도 함께 반환하도록 구현
* feat: 검색시 조회되는 공지의 댓글 수도 함께 반환하도록 구현
=> version 2.12.1

src/main/java/com/kustacks/kuring/admin/adapter/in/web/AdminQueryApiV2.java, src/main/java/com/kustacks/kuring/admin/application/port/in/AdminQueryUseCase.java, src/main/java/com/kustacks/kuring/admin/application/port/out/AdminUserReportPort.java, src/main/java/com/kustacks/kuring/admin/application/service/AdminQueryService.java, src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java, src/main/java/com/kustacks/kuring/common/exception/code/ErrorCode.java, src/main/java/com/kustacks/kuring/report/adapter/in/web/ReportCommandApiV2.java, src/main/java/com/kustacks/kuring/report/adapter/in/web/dto/ReportRequest.java, src/main/java/com/kustacks/kuring/report/adapter/out/exception/ReportExceptionHandler.java, src/main/java/com/kustacks/kuring/report/adapter/out/persistence/ReportPersistenceAdapter.java, src/main/java/com/kustacks/kuring/report/adapter/out/persistence/ReportRepository.java, src/main/java/com/kustacks/kuring/report/application/port/in/ReportCommandUseCase.java, src/main/java/com/kustacks/kuring/report/application/port/in/dto/AdminReportsResult.java, src/main/java/com/kustacks/kuring/report/application/port/out/ReportCommandPort.java, src/main/java/com/kustacks/kuring/report/application/service/ReportCommandService.java, src/main/java/com/kustacks/kuring/report/application/service/exception/ReportBusinessException.java, src/main/java/com/kustacks/kuring/report/domain/Report.java, src/main/java/com/kustacks/kuring/report/domain/ReportTargetType.java, src/main/resources/db/migration/V250530__Create_Report_Table.sql, src/test/java/com/kustacks/kuring/acceptance/AdminAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/AdminStep.java, src/test/java/com/kustacks/kuring/acceptance/ReportAcceptanceTest.java, src/test/java/com/kustacks/kuring/acceptance/ReportStep.java, src/test/java/com/kustacks/kuring/archunit/DependencyRuleTests.java
- 댓글 신고 API 추가
- 어드민 댓글 조회 API 추가
=> version 2.13.0

.github/workflows/dev.yml
#311 
- decrypt.sh실행 하도록 수정했습니다.
- 배포 시 로그를 절대경로에 나믹도록 수정했습니다.
- 이전 프로세스를 찾는 명령어를 수정했습니다.
=> fix: dev.yml decrpt 추가 및 sh 명령어 수정
